import { renderEnvironmentSection } from "./sections/environment.js";
import { ALL_SECTIONS } from "./sections/index.js";
import { getTemplate } from "./templates/index.js";
import type {
  ReadmeContext,
  ReadmeOptions,
  ReadmeResult,
  RenderedSection,
  SectionRenderer,
} from "./types.js";

const SECTION_REGISTRY = new Map<string, SectionRenderer>(
  ALL_SECTIONS.map((s) => [s.id, s]),
);

/** Register a custom section renderer at runtime. */
export function registerSection(renderer: SectionRenderer): void {
  SECTION_REGISTRY.set(renderer.id, renderer);
}

function buildTableOfContents(sections: RenderedSection[]): string {
  const lines = ["## Table of Contents", ""];
  for (const s of sections) {
    if (s.id === "overview") continue;
    const anchor = s.title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-");
    lines.push(`- [${s.title}](#${anchor})`);
  }
  return lines.join("\n");
}

export async function renderReadme(
  ctx: ReadmeContext,
  opts: ReadmeOptions = {},
): Promise<ReadmeResult> {
  const template = getTemplate(opts.template);

  // Determine which section IDs to render, in order
  const exclude = new Set(template.exclude ?? []);
  const ordered: string[] = [];

  for (const id of template.sections) {
    if (id === "*") {
      // Expand wildcard: all registered sections not already listed and not excluded
      const listed = new Set(template.sections.filter((s) => s !== "*"));
      for (const [regId] of SECTION_REGISTRY) {
        if (!listed.has(regId) && !exclude.has(regId)) {
          ordered.push(regId);
        }
      }
    } else if (!exclude.has(id)) {
      ordered.push(id);
    }
  }

  // Render each section
  const rendered: RenderedSection[] = [];

  for (const id of ordered) {
    const renderer = SECTION_REGISTRY.get(id);
    if (!renderer) continue;

    // Environment section has an async variant that reads .env files
    let section: RenderedSection | null = null;
    if (id === "environment") {
      section = await renderEnvironmentSection(ctx);
    } else {
      section = renderer.render(ctx);
    }

    if (section) rendered.push(section);
  }

  // Assemble markdown
  const parts: string[] = [];

  const overviewIdx = rendered.findIndex((s) => s.id === "overview");
  if (overviewIdx !== -1) {
    parts.push(rendered[overviewIdx]!.content.trimEnd());
    parts.push("");
  }

  // Table of contents (only for templates with 4+ sections)
  if (rendered.filter((s) => s.id !== "overview").length >= 3) {
    parts.push(buildTableOfContents(rendered));
    parts.push("");
    parts.push("---");
    parts.push("");
  }

  for (const section of rendered) {
    if (section.id === "overview") continue;
    parts.push(section.content.trimEnd());
    parts.push("");
  }

  // Footer
  parts.push("---");
  parts.push("");
  parts.push(
    "_Generated by [DocSmith](https://github.com/docsmith) — intelligent documentation for modern codebases._",
  );

  return {
    content: parts.join("\n"),
    sections: rendered.map((s) => s.id),
    templateUsed: template.name,
  };
}
