import type { AIProviderAdapter } from "../ai/types.js";
import { aiSummarize } from "./ai-summarizer.js";
import {
  apiFacts,
  architectureFacts,
  authFacts,
  businessLogicFacts,
  modulesFacts,
  purposeFacts,
} from "./facts.js";
import type {
  ExplainContext,
  ExplainOptions,
  ExplainSection,
  ExplainSectionId,
  RepoExplanation,
} from "./types.js";

// ── Section registry ──────────────────────────────────────────────────────────

const ALL_SECTIONS: ExplainSectionId[] = [
  "purpose",
  "architecture",
  "modules",
  "auth",
  "api",
  "business-logic",
];

const SECTION_TITLES: Record<ExplainSectionId, string> = {
  "purpose":        "Purpose",
  "architecture":   "Architecture",
  "modules":        "Core Modules",
  "auth":           "Authentication",
  "api":            "API Structure",
  "business-logic": "Business Logic",
};

const FACT_FNS: Record<ExplainSectionId, (ctx: ExplainContext) => string> = {
  "purpose":        purposeFacts,
  "architecture":   architectureFacts,
  "modules":        modulesFacts,
  "auth":           authFacts,
  "api":            apiFacts,
  "business-logic": businessLogicFacts,
};

// ── Renderer ──────────────────────────────────────────────────────────────────

export async function renderExplanation(
  ctx: ExplainContext,
  options: ExplainOptions,
  adapter?: AIProviderAdapter,
): Promise<RepoExplanation> {
  const sectionIds = options.sections ?? ALL_SECTIONS;
  const depth = options.depth ?? "standard";

  // Extract facts for every requested section
  const sectionData = sectionIds.map((id) => ({
    id,
    title: SECTION_TITLES[id],
    facts: FACT_FNS[id](ctx),
  }));

  let resultSections: ExplainSection[];
  let aiProvider: string | undefined;
  let aiModel: string | undefined;

  if (adapter !== undefined && adapter.isConfigured()) {
    // Summarize all sections in parallel — faster and each section is independent
    const settled = await Promise.allSettled(
      sectionData.map(async (s) => {
        const result = await aiSummarize(adapter, s.id, s.title, s.facts, depth, ctx.projectName);
        if (!aiModel) aiModel = result.model;
        if (!aiProvider) aiProvider = result.provider;
        return { ...s, content: result.content, aiGenerated: true };
      }),
    );

    resultSections = settled.map((outcome, i) => {
      const s = sectionData[i]!;
      if (outcome.status === "fulfilled") return outcome.value;
      // AI failed for this section — fall back to structured facts
      return { ...s, content: s.facts, aiGenerated: false };
    });
  } else {
    // No AI — structured facts are the output
    resultSections = sectionData.map((s) => ({
      ...s,
      content: s.facts,
      aiGenerated: false,
    }));
  }

  const content = assembleDoc(ctx.projectName, resultSections, aiProvider, aiModel);

  return {
    projectName: ctx.projectName,
    sections: resultSections,
    content,
    generatedAt: new Date().toISOString(),
    ...(aiProvider !== undefined && { aiProvider }),
    ...(aiModel !== undefined && { aiModel }),
  };
}

// ── Markdown assembly ─────────────────────────────────────────────────────────

function assembleDoc(
  projectName: string,
  sections: ExplainSection[],
  aiProvider?: string,
  aiModel?: string,
): string {
  const date = new Date().toISOString().split("T")[0];
  const credit = aiModel !== undefined
    ? `> Generated by DocSmith · ${date} · ${aiProvider}/${aiModel}`
    : `> Generated by DocSmith · ${date} · static analysis only`;

  const parts: string[] = [
    `# Repository Explanation: ${projectName}`,
    "",
    credit,
    "",
  ];

  for (const section of sections) {
    parts.push(`## ${section.title}`);
    parts.push("");
    parts.push(section.content);
    parts.push("");
  }

  return parts.join("\n");
}
