import { ALL_SECTIONS } from "./sections/index.js";
import { getTemplate } from "./templates/index.js";
import type {
  ContributingContext,
  ContributingOptions,
  ContributingResult,
  RenderedSection,
  SectionRenderer,
} from "./types.js";

const SECTION_REGISTRY = new Map<string, SectionRenderer>(
  ALL_SECTIONS.map((s) => [s.id, s]),
);

export function registerSection(renderer: SectionRenderer): void {
  SECTION_REGISTRY.set(renderer.id, renderer);
}

function buildTableOfContents(sections: RenderedSection[]): string {
  const lines = ["## Table of Contents", ""];
  for (const s of sections) {
    if (s.id === "intro") continue;
    const anchor = s.title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-");
    lines.push(`- [${s.title}](#${anchor})`);
  }
  return lines.join("\n");
}

export function renderContributing(
  ctx: ContributingContext,
  opts: ContributingOptions = {},
): ContributingResult {
  const template = getTemplate(opts.template);
  const exclude = new Set(template.exclude ?? []);
  const ordered: string[] = [];

  for (const id of template.sections) {
    if (id === "*") {
      const listed = new Set(template.sections.filter((s) => s !== "*"));
      for (const [regId] of SECTION_REGISTRY) {
        if (!listed.has(regId) && !exclude.has(regId)) ordered.push(regId);
      }
    } else if (!exclude.has(id)) {
      ordered.push(id);
    }
  }

  const rendered: RenderedSection[] = [];
  for (const id of ordered) {
    const renderer = SECTION_REGISTRY.get(id);
    if (!renderer) continue;
    const section = renderer.render(ctx);
    if (section) rendered.push(section);
  }

  const parts: string[] = [];

  const introIdx = rendered.findIndex((s) => s.id === "intro");
  if (introIdx !== -1) {
    parts.push(rendered[introIdx]!.content.trimEnd());
  }

  if (rendered.filter((s) => s.id !== "intro").length >= 3) {
    parts.push(buildTableOfContents(rendered));
  }

  for (const section of rendered) {
    if (section.id === "intro") continue;
    parts.push(section.content.trimEnd());
  }

  parts.push(
    "---\n\n_Generated by [DocSmith](https://github.com/docsmith) — intelligent documentation for modern codebases._",
  );

  return {
    content: parts.join("\n\n") + "\n",
    sections: rendered.map((s) => s.id),
    templateUsed: template.name,
  };
}
