"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Container } from "@/components/shared/Container";
import { SectionLabel } from "@/components/shared/SectionLabel";
import { AnimatedGroup, AnimatedItem } from "@/components/shared/AnimatedText";
import { fadeIn, viewport } from "@/styles/animations";
import { cn } from "@/lib/utils";
import { Check, Copy } from "lucide-react";

const tabs = [
  {
    label: "readme",
    file: "README.md",
    lang: "markdown",
    content: `# MyApp — Production-Ready REST API

> Auto-generated by DocSmith ✦

## Overview

MyApp is a **high-performance REST API** built with Express.js and
TypeScript, following a clean architecture pattern with domain-driven
design principles.

### Architecture

\`\`\`
src/
├── domain/          # Business logic & entities
├── application/     # Use cases & services
├── infrastructure/  # DB, HTTP, external APIs
└── interface/       # Controllers & route handlers
\`\`\`

## Quick start

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`

## API Endpoints

| Method | Path              | Description           |
|--------|-------------------|-----------------------|
| GET    | /api/users        | List users            |
| POST   | /api/users        | Create user           |
| GET    | /api/users/:id    | Get user by ID        |
| DELETE | /api/users/:id    | Delete user           |`,
  },
  {
    label: "api-docs",
    file: "API_DOCS.md",
    lang: "markdown",
    content: `# API Documentation

## Authentication

All endpoints require a Bearer token in the \`Authorization\` header.

\`\`\`
Authorization: Bearer <your-token>
\`\`\`

## Users

### GET /api/users

Returns paginated list of users.

**Query params**

| Param  | Type   | Default | Description      |
|--------|--------|---------|------------------|
| page   | number | 1       | Page number      |
| limit  | number | 20      | Items per page   |
| search | string | —       | Filter by name   |

**Response**

\`\`\`json
{
  "data": [
    {
      "id": "usr_01HXYZ",
      "name": "Alice",
      "email": "alice@example.com",
      "createdAt": "2025-01-15T10:30:00Z"
    }
  ],
  "meta": {
    "total": 248,
    "page": 1,
    "limit": 20
  }
}
\`\`\``,
  },
  {
    label: "contributing",
    file: "CONTRIBUTING.md",
    lang: "markdown",
    content: `# Contributing to MyApp

Thank you for your interest in contributing! This guide covers
everything you need to get started.

## Development setup

\`\`\`bash
git clone https://github.com/you/myapp
cd myapp
npm install
npm run dev
\`\`\`

## Branch strategy

| Branch      | Purpose                       |
|-------------|-------------------------------|
| \`main\`      | Production-ready code         |
| \`dev\`       | Integration branch            |
| \`feat/*\`    | New features                  |
| \`fix/*\`     | Bug fixes                     |

## Pull request checklist

- [ ] Tests pass (\`npm test\`)
- [ ] Types check (\`npm run type-check\`)
- [ ] Lint passes (\`npm run lint\`)
- [ ] Docs updated if API changed

## Commit conventions

We follow [Conventional Commits](https://www.conventionalcommits.org):
\`feat:\`, \`fix:\`, \`chore:\`, \`docs:\``,
  },
];

export function CodeDemo() {
  const [activeTab, setActiveTab] = useState(0);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    void navigator.clipboard.writeText(tabs[activeTab].content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <section id="demo" className="relative py-28 overflow-hidden">
      {/* Background */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute right-1/4 top-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-brand-500/6 blur-[100px] rounded-full" />
      </div>

      <Container>
        <AnimatedGroup className="text-center mb-16 space-y-4">
          <AnimatedItem>
            <SectionLabel label="Output preview" />
          </AnimatedItem>
          <AnimatedItem>
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight text-balance">
              See what DocSmith{" "}
              <span className="text-gradient-brand">generates</span>
            </h2>
          </AnimatedItem>
          <AnimatedItem>
            <p className="mx-auto max-w-lg text-lg text-muted-foreground text-balance">
              Real output from a real codebase — accurate, structured,
              and ready to ship.
            </p>
          </AnimatedItem>
        </AnimatedGroup>

        {/* Code window */}
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={viewport}
          variants={fadeIn}
          className="rounded-2xl border border-border bg-surface overflow-hidden shadow-2xl shadow-black/50"
        >
          {/* Title bar */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-surface-raised">
            <div className="flex items-center gap-3">
              <div className="flex gap-1.5">
                <div className="h-3 w-3 rounded-full bg-red-500/70" />
                <div className="h-3 w-3 rounded-full bg-amber-500/70" />
                <div className="h-3 w-3 rounded-full bg-emerald-500/70" />
              </div>
              <span className="text-xs text-muted-foreground font-mono">
                {tabs[activeTab].file}
              </span>
            </div>

            <button
              onClick={handleCopy}
              className={cn(
                "flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-lg",
                "border border-border text-muted-foreground",
                "hover:text-foreground hover:border-brand-500/40 hover:bg-brand-500/5",
                "transition-all duration-150"
              )}
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3 text-emerald-400" />
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3" />
                  Copy
                </>
              )}
            </button>
          </div>

          {/* Tabs */}
          <div className="flex items-center gap-0 border-b border-border px-4 overflow-x-auto">
            {tabs.map((tab, i) => (
              <button
                key={tab.label}
                onClick={() => setActiveTab(i)}
                className={cn(
                  "px-4 py-2.5 text-sm font-medium transition-all duration-150 whitespace-nowrap border-b-2 -mb-px",
                  i === activeTab
                    ? "border-brand-400 text-foreground"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                )}
              >
                {tab.file}
              </button>
            ))}
          </div>

          {/* Content */}
          <div className="relative overflow-hidden" style={{ maxHeight: 440 }}>
            <AnimatePresence mode="wait">
              <motion.pre
                key={activeTab}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -8 }}
                transition={{ duration: 0.2 }}
                className="p-6 font-mono text-sm leading-relaxed text-foreground/90 overflow-auto"
                style={{ maxHeight: 440 }}
              >
                <code className="whitespace-pre">{tabs[activeTab].content}</code>
              </motion.pre>
            </AnimatePresence>

            {/* Bottom fade */}
            <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-surface to-transparent pointer-events-none" />
          </div>
        </motion.div>
      </Container>
    </section>
  );
}
