import type { ApiFramework } from "../analyzer/types.js";
import type { AuthStrategy, RouteEntry } from "../analyzer/routes/types.js";
import { displayPath } from "./collector.js";
import type { ApiDocsContext, ApiDocsResult, CollectedRoute, RouteTag } from "./types.js";

// ---- display maps ----

const FRAMEWORK_NAMES: Record<ApiFramework, string> = {
  "nextjs-app": "Next.js App Router",
  "nextjs-pages": "Next.js Pages Router",
  express: "Express",
  hono: "Hono",
  fastify: "Fastify",
  trpc: "tRPC",
  unknown: "Unknown",
};

const AUTH_LABELS: Record<string, string> = {
  jwt: "JWT Bearer",
  bearer: "Bearer Token",
  session: "Session Cookie",
  apikey: "API Key",
  oauth: "OAuth 2.0",
  basic: "HTTP Basic",
  custom: "Custom",
  none: "None",
  unknown: "Unknown",
};

const AUTH_HINTS: Record<string, string> = {
  jwt: "Pass `Authorization: Bearer <token>` header",
  bearer: "Pass `Authorization: Bearer <token>` header",
  session: "Include session cookie received at login",
  apikey: "Pass `X-API-Key: <key>` header",
  oauth: "Pass `Authorization: Bearer <access_token>` header",
  basic: "Pass `Authorization: Basic <base64(user:pass)>` header",
  custom: "Refer to middleware implementation",
};

const MIDDLEWARE_PURPOSE_LABELS: Record<string, string> = {
  cors: "CORS",
  logging: "Logging",
  ratelimit: "Rate limiting",
  parsing: "Body parsing",
  compression: "Response compression",
  validation: "Request validation",
  error: "Error handling",
  unknown: "",
};

// ---- entry point ----

export function renderApiDocs(ctx: ApiDocsContext): ApiDocsResult {
  const lines: string[] = [];

  lines.push(...renderHeader(ctx));
  lines.push("");
  lines.push(...renderToc(ctx));
  lines.push("");
  lines.push(...renderOverview(ctx));
  lines.push("");

  const authSummary = buildAuthSummary(ctx.routes);
  if (authSummary.strategies.length > 0) {
    lines.push(...renderAuthentication(authSummary));
    lines.push("");
  }

  lines.push(...renderAllRoutes(ctx));

  return {
    content: lines.join("\n").trimEnd() + "\n",
    routeCount: ctx.routes.length,
    tagCount: ctx.tags.length,
    framework: ctx.framework,
  };
}

// ---- header ----

function renderHeader(ctx: ApiDocsContext): string[] {
  const count = ctx.routes.length;
  const fw = FRAMEWORK_NAMES[ctx.framework] ?? ctx.framework;
  return [
    `# ${ctx.title}`,
    "",
    `> Auto-generated by [DocSmith](https://github.com/0xdevabir/docsmith) · ` +
      `**${count}** route${count === 1 ? "" : "s"} · ${fw}`,
  ];
}

// ---- table of contents ----

function renderToc(ctx: ApiDocsContext): string[] {
  const lines: string[] = [];
  lines.push("## Table of Contents");
  lines.push("");
  lines.push("- [Overview](#overview)");

  const authSummary = buildAuthSummary(ctx.routes);
  if (authSummary.strategies.length > 0) {
    lines.push("- [Authentication](#authentication)");
  }

  lines.push("- [Routes](#routes)");
  for (const tag of ctx.tags) {
    const anchor = tag.name.toLowerCase().replace(/\s+/g, "-").replace(/[^\w-]/g, "");
    lines.push(`  - [${tag.name}](#${anchor})`);
  }

  return lines;
}

// ---- overview ----

function renderOverview(ctx: ApiDocsContext): string[] {
  const lines: string[] = [];
  lines.push("## Overview");
  lines.push("");

  const authStrategies = [
    ...new Set(
      ctx.routes
        .map((r) => r.entry.auth.strategy)
        .filter((s): s is Exclude<AuthStrategy, "none"> => s !== "none"),
    ),
  ];

  const rows: [string, string][] = [
    ["**Framework**", FRAMEWORK_NAMES[ctx.framework] ?? ctx.framework],
  ];

  if (ctx.baseUrl !== undefined) {
    rows.push(["**Base URL**", `\`${ctx.baseUrl}\``]);
  }

  rows.push(["**Routes**", String(ctx.routes.length)]);
  rows.push(["**Route groups**", String(ctx.tags.length)]);
  rows.push([
    "**Auth**",
    authStrategies.length > 0
      ? authStrategies.map((s) => AUTH_LABELS[s] ?? s).join(", ")
      : "None detected",
  ]);

  lines.push("| | |");
  lines.push("|---|---|");
  for (const [k, v] of rows) {
    lines.push(`| ${k} | ${v} |`);
  }

  return lines;
}

// ---- authentication ----

interface AuthSummary {
  strategies: string[];
  hasRoles: boolean;
  hasScopes: boolean;
}

function buildAuthSummary(routes: CollectedRoute[]): AuthSummary {
  const strategies = new Set<string>();
  let hasRoles = false;
  let hasScopes = false;

  for (const { entry } of routes) {
    const auth = entry.auth;
    if (!auth?.protected) continue;
    if (auth.strategy !== "none") {
      strategies.add(auth.strategy);
    }
    if (auth.roles.length > 0) hasRoles = true;
    if (auth.scopes.length > 0) hasScopes = true;
  }

  return { strategies: [...strategies], hasRoles, hasScopes };
}

function renderAuthentication(summary: AuthSummary): string[] {
  const lines: string[] = [];
  lines.push("## Authentication");
  lines.push("");
  lines.push(
    "Routes marked with 🔒 require authentication. " +
      "Requests without valid credentials receive `401 Unauthorized`.",
  );
  lines.push("");

  lines.push("| Strategy | How to authenticate |");
  lines.push("|---|---|");
  for (const strategy of summary.strategies) {
    const label = AUTH_LABELS[strategy] ?? strategy;
    const hint = AUTH_HINTS[strategy] ?? "Refer to implementation";
    lines.push(`| **${label}** | ${hint} |`);
  }

  if (summary.hasRoles) {
    lines.push("");
    lines.push(
      "> **Role-based access** — some routes restrict access by role. " +
        "Required roles are listed per-route below.",
    );
  }

  if (summary.hasScopes) {
    lines.push("");
    lines.push(
      "> **Scoped access** — some routes enforce OAuth scopes. " +
        "Required scopes are listed per-route below.",
    );
  }

  return lines;
}

// ---- routes section ----

function renderAllRoutes(ctx: ApiDocsContext): string[] {
  const lines: string[] = [];
  lines.push("## Routes");

  if (ctx.routes.length === 0) {
    lines.push("");
    lines.push(
      "> No API routes were detected. Make sure the project uses a supported " +
        "framework (Next.js, Express, Hono, Fastify) and re-run without `--skip-analysis`.",
    );
    return lines;
  }

  for (const tag of ctx.tags) {
    lines.push("");
    lines.push(`### ${tag.name}`);
    lines.push("");

    for (let i = 0; i < tag.routes.length; i++) {
      const cr = tag.routes[i];
      if (cr === undefined) continue;
      lines.push(...renderRoute(cr, ctx.baseUrl));
      if (i < tag.routes.length - 1) {
        lines.push("");
        lines.push("---");
      }
    }
  }

  return lines;
}

function renderRoute(cr: CollectedRoute, baseUrl: string | undefined): string[] {
  const { entry, relativePath } = cr;
  const lines: string[] = [];

  const routePath = displayPath(entry);
  const methods = entry.methods.length > 0 ? entry.methods : ["UNKNOWN"];
  const isProtected = entry.auth?.protected === true;

  // Heading: method badge(s) + path + optional lock
  const methodBadges = methods.map((m) => `\`${m}\``).join(" ");
  lines.push(`#### ${methodBadges} \`${routePath}\`${isProtected ? " 🔒" : ""}`);
  lines.push("");

  if (entry.description) {
    lines.push(entry.description.trim());
    lines.push("");
  }

  // Meta table
  const meta: [string, string][] = [];

  if (isProtected && entry.auth) {
    const { strategy, roles, scopes } = entry.auth;
    let val = `🔒 ${AUTH_LABELS[strategy] ?? strategy}`;
    if (roles.length > 0) val += ` · roles: \`${roles.join("`, `")}\``;
    if (scopes.length > 0) val += ` · scopes: \`${scopes.join("`, `")}\``;
    meta.push(["**Auth**", val]);
  } else {
    meta.push(["**Auth**", "None"]);
  }

  meta.push(["**Handler**", `\`${entry.handler}\``]);
  meta.push(["**Framework**", FRAMEWORK_NAMES[entry.framework] ?? entry.framework]);
  meta.push(["**Source**", `\`${relativePath}\``]);

  if (baseUrl !== undefined && routePath !== "(dynamic)") {
    meta.push(["**Example**", `\`${baseUrl.replace(/\/$/, "")}${routePath}\``]);
  }

  lines.push("| | |");
  lines.push("|---|---|");
  for (const [k, v] of meta) {
    lines.push(`| ${k} | ${v} |`);
  }
  lines.push("");

  // Path parameters
  const pathParams = (entry.params ?? []).filter((p) => p.in === "path");
  if (pathParams.length > 0) {
    lines.push("**Path Parameters**");
    lines.push("");
    lines.push("| Name | Required | Type |");
    lines.push("|---|---|---|");
    for (const p of pathParams) {
      lines.push(`| \`${p.name}\` | ${p.required ? "✓" : "No"} | \`${p.schema ?? "string"}\` |`);
    }
    lines.push("");
  }

  // Request body validation
  const bodyVal = (entry.validation ?? []).filter((v) => v.target === "body");
  if (bodyVal.length > 0) {
    lines.push("**Request Body**");
    lines.push("");
    for (const v of bodyVal) {
      const schema = v.schemaName ? `\`${v.schemaName}\`` : "_(inline schema)_";
      const lib = v.lib !== "unknown" ? ` · validated with **${v.lib}**` : "";
      lines.push(`- Schema: ${schema}${lib}`);
    }
    lines.push("");
  }

  // Query parameter validation
  const queryVal = (entry.validation ?? []).filter((v) => v.target === "query");
  if (queryVal.length > 0) {
    lines.push("**Query Parameters**");
    lines.push("");
    for (const v of queryVal) {
      const schema = v.schemaName ? `\`${v.schemaName}\`` : "_(inline schema)_";
      const lib = v.lib !== "unknown" ? ` · validated with **${v.lib}**` : "";
      lines.push(`- Schema: ${schema}${lib}`);
    }
    lines.push("");
  }

  // Header validation
  const headerVal = (entry.validation ?? []).filter((v) => v.target === "headers");
  if (headerVal.length > 0) {
    lines.push("**Required Headers**");
    lines.push("");
    for (const v of headerVal) {
      const schema = v.schemaName ? `\`${v.schemaName}\`` : "_(inline schema)_";
      lines.push(`- Schema: ${schema}`);
    }
    lines.push("");
  }

  // Non-auth middleware
  const nonAuthMw = (entry.middleware ?? []).filter(
    (m) => m.purpose !== "auth" && m.purpose !== "validation",
  );
  if (nonAuthMw.length > 0) {
    lines.push("**Middleware**");
    lines.push("");
    for (const m of nonAuthMw) {
      const label = m.purpose !== "unknown" ? MIDDLEWARE_PURPOSE_LABELS[m.purpose] ?? "" : "";
      const suffix = label ? ` _(${label})_` : "";
      lines.push(`- \`${m.name}\`${suffix}`);
    }
    lines.push("");
  }

  // Responses
  lines.push(...renderResponses(entry));

  return lines;
}

function renderResponses(entry: RouteEntry): string[] {
  const lines: string[] = [];
  const method = entry.methods[0] ?? "GET";
  const isProtected = entry.auth?.protected === true;
  const hasValidation = (entry.validation ?? []).length > 0;

  lines.push("**Responses**");
  lines.push("");
  lines.push("| Status | Description |");
  lines.push("|---|---|");
  lines.push(`| \`${successStatus(method)}\` | ${successDescription(method)} |`);

  if (isProtected) {
    lines.push(`| \`401\` | Unauthorized — missing or invalid credentials |`);
    if ((entry.auth?.roles?.length ?? 0) > 0) {
      lines.push(`| \`403\` | Forbidden — insufficient permissions |`);
    }
  }

  if (hasValidation) {
    lines.push(`| \`422\` | Unprocessable Entity — validation failed |`);
  }

  lines.push(`| \`500\` | Internal Server Error |`);
  lines.push("");

  return lines;
}

function successStatus(method: string): string {
  if (method === "POST") return "201";
  if (method === "DELETE") return "204";
  return "200";
}

function successDescription(method: string): string {
  const map: Record<string, string> = {
    GET: "OK — returns requested resource",
    POST: "Created — resource created",
    PUT: "OK — resource replaced",
    PATCH: "OK — resource updated",
    DELETE: "No Content — resource deleted",
    HEAD: "OK — headers only",
    OPTIONS: "OK — allowed methods",
    ALL: "OK",
  };
  return map[method] ?? "OK";
}
