import {
  generateArchitectureDiagram,
  generateDependencyDiagram,
  generateModuleRelationsDiagram,
  generateRequestFlowDiagram,
} from "./generators/index.js";
import type {
  DiagramContext,
  DiagramGenerator,
  DiagramResult,
  DiagramType,
  DiagramsOutput,
} from "./types.js";

const ALL_TYPES: DiagramType[] = [
  "architecture",
  "dependency",
  "request-flow",
  "module-relations",
];

const GENERATORS: Record<DiagramType, DiagramGenerator> = {
  "architecture":     generateArchitectureDiagram,
  "dependency":       generateDependencyDiagram,
  "request-flow":     generateRequestFlowDiagram,
  "module-relations": generateModuleRelationsDiagram,
};

export function renderDiagrams(ctx: DiagramContext): DiagramsOutput {
  const types = ctx.options.types ?? ALL_TYPES;
  const diagrams: DiagramResult[] = [];

  for (const type of types) {
    const generator = GENERATORS[type];
    const result = generator(ctx);
    if (result !== null) {
      diagrams.push(result);
    }
  }

  return {
    diagrams,
    content: buildDoc(diagrams),
    diagramCount: diagrams.length,
  };
}

function buildDoc(diagrams: DiagramResult[]): string {
  const lines: string[] = [
    "# Diagrams\n",
    `> Generated by DocSmith — ${new Date().toISOString().split("T")[0]}\n`,
  ];

  for (const d of diagrams) {
    lines.push(`## ${d.title}\n`);
    lines.push(d.markdown);
    lines.push("");
  }

  if (diagrams.length === 0) {
    lines.push("_No diagrams generated. Run with analysis enabled._\n");
  }

  return lines.join("\n");
}
